# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DataStories.ML Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
    Personal Blog on Data Science, Digital Transformation, Big Tech, AI for Social Good and all the other stuff. 
twitter_username: username
github_username: username
minimal_mistakes_skin: dark2 
# "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _PL
  - _EN

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
#  - jekyll-archives

author:
  name   : "Teresa Kubacka"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data scientist, physicist, musician, critical thinker."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://datastories.ml"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tkubacka/"
    - label: "Medium"
      icon: "fab fa-medium"
      url: "https://medium.com/@teresa.kubacka"

footer:
  links:


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # blogposts PL 
  - scope:
      path: ""
      type: PL
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # blogposts EN 
  - scope:
      path: ""
      type: EN
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections:
  PL:
    output: true
    permalink: /:categories/:title/
  EN:
    output: true
    permalink: /:categories/:title/

excerpt_separator: "<!--more-->"